language: node_js
node_js:
  - '7'
  - '6'
  - '4'
branches:
  only:
  - master
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_install:
  - 'npm install --global npm'
before_script:
  - 'npm prune'
after_success:
  - 'npm test'